### ISSUE TITLE
Feature: User can search for a wallet 

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to search for a Bitcoin wallet address.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to type a Bitcoin wallet address into one of the forms to search their address in the blockchain. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-13 at 3 19 49 PM](https://user-images.githubusercontent.com/96788421/163280503-cdfe8f7a-f6b7-4179-acf1-22483084515d.png)
![Screen Shot 2022-04-13 at 3 19 57 PM](https://user-images.githubusercontent.com/96788421/163280504-bc453664-342d-495a-a149-66ced6a2bc70.png)
![Screen Shot 2022-04-13 at 3 26 39 PM](https://user-images.githubusercontent.com/96788421/163280507-69933fbe-240b-4a8f-bb06-18b7280d658a.png)
![Screen Shot 2022-04-13 at 3 27 52 PM](https://user-images.githubusercontent.com/96788421/163280508-3097deef-8818-4002-92c8-6f204dfaa0a4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include schema design

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the user to have a homepage
- [x] Update component to include a form for the user to search with

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
