### ISSUE TITLE
Feature 10: User can text themselves or another the search results

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can text themselves or another the search results

## 📐 Functionality

User will be able to click the share button that will pop a modal up and text a number the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-16 at 4 44 12 PM](https://user-images.githubusercontent.com/96788421/163694608-78b42c34-0417-4ba7-9aa3-71918a459709.png)
![Screen Shot 2022-04-16 at 4 44 07 PM](https://user-images.githubusercontent.com/96788421/163694609-582ac9c9-ad4d-436e-a12f-c14b457c439d.png)
![Screen Shot 2022-04-16 at 4 44 02 PM](https://user-images.githubusercontent.com/96788421/163694610-25311ab0-09e2-4a69-9866-961825db727b.png)
![Screen Shot 2022-04-16 at 4 44 26 PM](https://user-images.githubusercontent.com/96788421/163694611-8d57046c-06e9-46f9-867b-b06be258af41.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Update component to have a share button on the result page
- [ ] Have a modal pop up on click for the user to be able to text the page.

### 🧑‍⚕️ Clean Up

- [ ] Use the twilio api to add functionality to the page
- [ ] Add styling to fit figma
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
