### ISSUE TITLE
Feature 8: User can see the price of Bitcoin on the Navbar

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the price of Bitcoin on the Navbar

## 📐 Functionality

The user will now be able to see the price on the navbar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-16 at 4 53 52 PM](https://user-images.githubusercontent.com/96788421/163694765-9fd44283-f099-48d3-9297-22d0c2552bcb.png)
![Screen Shot 2022-04-16 at 4 55 42 PM](https://user-images.githubusercontent.com/96788421/163694767-8a0e0013-aaa4-487f-b131-ff2ec433840a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component to fetch the price
- [ ] Update component to view the price

### 🧑‍⚕️ Clean Up

- [ ] Add styling to fit the figma
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
