### ISSUE TITLE
Feature: User can view their search results

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their search results including last 3 transactions involving the wallet

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to search for a wallet and now see the results of their search
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-14 at 1 51 02 PM](https://user-images.githubusercontent.com/96788421/163473198-18ff0a1c-717b-4768-8d0d-2ac0350d8a12.png)
![Screen Shot 2022-04-14 at 1 51 12 PM](https://user-images.githubusercontent.com/96788421/163473200-58416a26-ef82-469f-8c74-e3587ac868c7.png)
![Screen Shot 2022-04-16 at 9 21 55 AM](https://user-images.githubusercontent.com/96788421/163683241-aa5e2c9a-d513-46a3-9ccd-808c5fc60b12.png)

![Screen Shot 2022-04-14 at 1 51 31 PM](https://user-images.githubusercontent.com/96788421/163473202-c4337cc2-3c3d-490f-9fdb-baf03e39d6ba.png)

![Screen Shot 2022-04-16 at 9 25 07 AM](https://user-images.githubusercontent.com/96788421/163683235-7266446f-f8c4-41f4-83cf-9cc1e0199710.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component for the user to see their results
- [x] Update component to show the results
- [x] change submit event listeners in search forms to update the window.location.hash including the address- `window.locations.hash = ‘search-results?address=’ + userInput
- [x] define a SearchResults component
- [x] move data fetching into the search results component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
