### ISSUE TITLE
Feature 3: User can view the QR code of a wallet address

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the QR code of a wallet address

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to search for their wallet address and see the actual QR code for their search.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-04-16 at 11 01 34 AM](https://user-images.githubusercontent.com/96788421/163686391-6cc77468-793b-4a9b-8780-2c0676845b51.png)

![Screen Shot 2022-04-16 at 11 01 59 AM](https://user-images.githubusercontent.com/96788421/163686394-19a0
![Screen Shot 2022-04-19 at 8 25 44 AM](https://user-images.githubusercontent.com/96788421/164040648-5a2a0335-f57c-4b79-a4c5-c1f50a4ab423.png)
![Screen Shot 2022-04-19 at 8 26 59 AM](https://user-images.githubusercontent.com/96788421/164040653-ef348f18-26cb-4c23-9fdc-6eef4314910d.png)
80fb-88ae-41d6-ade1-43c553c76fc2.png)

![Screen Shot 2022-04-18 at 8 36 20 PM](https://user-images.githubusercontent.com/96788421/164039328-9177fbec-f6b5-44ce-b1ec-e8d6fcabbc9f.png)
![Screen Shot 2022-04-18 at 8 36 20 PM](https://user-images.githubusercontent.com/96788421/164039568-ce2fd645-4910-4840-b7c8-a7e27eb8ebdc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to fetch the img url of the URL code 
       -concatenate the user input to the fetch request
- [x] Update component to show the URL img inside of the result card

### 🧑‍⚕️ Clean Up

- [x] Make the image fit seamlessly into the card
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
