### ISSUE TITLE
Feature 4: User can bookmark a wallet to database(address, amount, and # of transactions)

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can bookmark a wallet to database(address, amount, and # of transactions)

## 📐 Functionality

User can click on the star icon on the results page and the information will be sent to the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-16 at 11 12 26 AM](https://user-images.githubusercontent.com/96788421/163686744-3059b476-4efe-42a6-acb7-e9f9de1258ba.png)
![Screen Shot 2022-04-16 at 11 12 42 AM](https://user-images.githubusercontent.com/96788421/163686745-97f002fc-efbe-4285-af1b-b312e7ee2c99.png)
![Screen Shot 2022-04-16 at 11 13 44 AM](https://user-images.githubusercontent.com/96788421/163686746-100ada19-b7a2-4d6c-a268-a2d882ce65a2.png)
![Screen Shot 2022-04-19 at 11 05 52 AM](https://user-images.githubusercontent.com/96788421/164067759-9d6b53bb-8b79-4d26-8ea5-5ecc21601ebb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert the user bookmarks

### ☁️ Server

- [x] Update `server/index.js` to respond to the post request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component to respond to the post request.

### 🧑‍⚕️ Clean Up

- [x] Add icon to fit figma
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
