### ISSUE TITLE
Feature 5: User can view their bookmarks.

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now view their bookmarks.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will now be able to click the bookmark icon and see their bookmarks.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-04-16 at 3 55 17 PM](https://user-images.githubusercontent.com/96788421/163693858-9d6d37e1-876b-4902-b762-4640156ef19a.png)
![Screen Shot 2022-04-16 at 3 55 09 PM](https://user-images.githubusercontent.com/96788421/163693860-ca9ff1d6-dd9d-491d-aa0c-f6d1195b6d63.png)
![Screen Shot 2022-04-16 at 3 55 25 PM](https://user-images.githubusercontent.com/96788421/163693861-1e7f9991-651c-41fd-97a9-b59bcb59b81e.png)
![Screen Shot 2022-04-16 at 3 55 36 PM](https://user-images.githubusercontent.com/96788421/163693862-61ea8072-6257-433d-93da-737db1aefbca.png)
![Screen Shot 2022-04-16 at 3 56 19 PM](https://user-images.githubusercontent.com/96788421/163693863-e77d8c1a-8597-4f50-b137-ceb8fcecb538.png)
![Screen Shot 2022-04-16 at 3 56 25 PM](https://user-images.githubusercontent.com/96788421/163693864-ac4258ac-711d-49f6-abe1-bd62bec95376.png)
![Screen Shot 2022-04-16 at 3 56 30 PM](https://user-images.githubusercontent.com/96788421/163693866-d62ae951-8ea6-4938-b707-5bab076da989.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to receive a get request to get the bookmarks.

### ☁️ Server

- [ ] Update `server/index.js` to receive get request to see the bookmarks.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to view barkmarks
- [ ] Update component to change the hash for the bookmark page.

### 🧑‍⚕️ Clean Up

- [ ] Update the bookmark page to fit the figma
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
