### ISSUE TITLE
Feature 6: User can remove their bookmarks

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove their bookmarks 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user click the icon to remove the bookmark.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-04-16 at 4 20 24 PM](https://user-images.githubusercontent.com/96788421/163694213-f8fb9a40-7bb5-4b79-b84e-7afea8615eee.png)
![Screen Shot 2022-04-16 at 4 20 18 PM](https://user-images.githubusercontent.com/96788421/163694214-59aba907-3b12-49e8-9053-d6ea97044294.png)
![Screen Shot 2022-04-16 at 4 20 13 PM](https://user-images.githubusercontent.com/96788421/163694215-ee9e0eb9-bfff-4a47-84bc-70d550ccf425.png)
![Screen Shot 2022-04-16 at 4 23 25 PM](https://user-images.githubusercontent.com/96788421/163694216-e5417d2a-1749-4b5c-9d77-5874e92120ce.png)
![Screen Shot 2022-04-16 at 4 23 31 PM](https://user-images.githubusercontent.com/96788421/163694218-82fee70e-591b-4099-88ef-665aebe6500e.png)
![Screen Shot 2022-04-16 at 4 23 37 PM](https://user-images.githubusercontent.com/96788421/163694219-6d8ee8be-2a00-4f2d-8b90-2458bb9f3aa8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `data.sql` to deal with the post request for user to delete the bookmark.

### ☁️ Server

- [ ] Update `server/index.js` to deal with the post request for the user to be able to delete the 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update the bookmark component to deal with the delete request. 

### 🧑‍⚕️ Clean Up

- [ ] Style the page to fit the figma
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
