### ISSUE TITLE
Feature 7: User can see more relevant data on the home page. 

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/final-project-template#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see more relevant data on the home page including the last 3 blocks mined on the homepage and current transaction fees and estimated adjustment fees

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see more relevant information of the blockchain.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-04-22 at 1 09 38 PM](https://user-images.githubusercontent.com/96788421/164787714-5cfc1a47-24fc-4c71-9839-656b5e0198dd.png)
![Screen Shot 2022-04-22 at 1 10 34 PM](https://user-images.githubusercontent.com/96788421/164787726-1f014b10-3c28-4fe8-8fef-0fe948b20109.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to fetch the necessary data
- [x] Update component to view the new component

### 🧑‍⚕️ Clean Up

- [x] Add styling to fit the figma
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
